# Generated by Django 2.2 on 2020-06-03 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('title', models.TextField()),
                ('placeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detailsUrl', models.URLField(max_length=250)),
            ],
        ),
    ]
