# Generated by Django 2.2.5 on 2020-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
